name: NanoPi-R2S RK3328 OpenWrt 19.07 Fat Build

on:
  push:
    paths:
      - '.github/workflows/NanoPi-R2S_Openwrt1907_Fat.yml'
      - 'r2s-rk3328-fat.config'
      - 'CHANGELOG.md'

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Initialize Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
          sudo docker image prune -a -f
          sudo apt-get -y install upx-ucl unzip
          sudo apt-get -y purge dotnet* ghc* google* llvm* mysql* php* zulu* firefox hhvm
          sudo apt-get -y autoremove --purge          
          wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash

      - name: Install Repo
        run: |
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/

      - name: Download Source
        run: |
          rm -rf friendlywrt-rk3328
          mkdir friendlywrt-rk3328
          cd friendlywrt-rk3328
          repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v19.07.1 -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle
          repo sync -c --no-clone-bundle -j8

      - name: Merge LEDE
        run: |
          cd friendlywrt-rk3328
          git clone https://github.com/coolsnowwolf/lede
          cd friendlywrt
          cp -r ../lede/package/lean package/
          cp -r ../lede/package/utils/lua5.3 package/utils/
          sed -i '/.*src-git packages.*/d'  feeds.conf.default
          sed -i '/.*src-git luci.*/d'      feeds.conf.default
          sed -i '$a src-git packages   https://github.com/coolsnowwolf/packages.git;master'   feeds.conf.default
          sed -i '$a src-git luci       https://github.com/coolsnowwolf/luci.git;master'       feeds.conf.default
          sed -i '$a src-git xiaorouji  https://github.com/xiaorouji/openwrt-package;master'   feeds.conf.default
          
      - name: Install Extra Packages
        run: |
          cd friendlywrt-rk3328/friendlywrt/package

          git clone https://github.com/frainzy1477/luci-app-clash
          sed -i 's/SUBMENU:=2. Clash/SUBMENU:=3. Applications/' luci-app-clash/Makefile

          git clone https://github.com/rufengsuixing/luci-app-adguardhome
          git clone https://github.com/tty228/luci-app-serverchan
          
          git clone https://github.com/fw876/helloworld
          mv helloworld/luci-app-ssr-plus/ .
          rm -rf helloworld/
          
          rm -rf lean/luci-theme-argon
          git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git

          git clone -b master https://github.com/vernesong/OpenClash
          mv OpenClash/luci-app-openclash/ .
          rm -rf OpenClash/
          
          git clone https://github.com/songchenwen/nanopi-r2s
          mv nanopi-r2s/luci-app-r2sflasher/ .
          mv nanopi-r2s/scripts/ ../../..
          rm -rf nanopi-r2s/          
          
          git clone https://github.com/pymumu/openwrt-smartdns ./smartdns
          
          git clone https://github.com/jerrykuku/node-request.git
          git clone https://github.com/jerrykuku/luci-app-jd-dailybonus.git  
          git clone https://github.com/honwen/luci-app-aliddns.git

          git clone https://github.com/kenzok8/openwrt-packages
          mv openwrt-packages/luci-app-advancedsetting/ .
          mv openwrt-packages/luci-app-smartdns/ .
          rm -rf openwrt-packages
          
          git clone -b master https://github.com/pexcn/openwrt-chinadns-ng ./chinadns-ng
          git clone -b luci https://github.com/pexcn/openwrt-chinadns-ng ./luci-app-chinadns-ng
          sed -i '/CATEGORY/a\\tSUBMENU:=3. Applications' ./luci-app-chinadns-ng/Makefile
          
      - name: Download OpenClash Binary
        run: |
          mkdir -p friendlywrt-rk3328/friendlywrt/package/base-files/files/etc/openclash/core
          
          cd friendlywrt-rk3328/friendlywrt/package/base-files/files/etc
          wget -qO- https://github.com/vernesong/OpenClash/releases/download/Clash/clash-linux-armv8.tar.gz | tar xzO > ./openclash/core/clash
          wget -qO- https://github.com/vernesong/OpenClash/releases/download/TUN/clash-linux-armv8.tar.gz | tar xzO > ./openclash/core/clash_game
          chmod +x ./openclash/core/clash ./openclash/core/clash_game
          ln -s openclash clash
          
#     - name: Fix IPv6 Firewall (ip6tables)
#       run: |
#         cd friendlywrt-rk3328/friendlywrt/package/base-files/files/etc
#         if [ -f firewall.user ]; then
#             echo "iface_linux=pppoe-wan"                                          >> firewall.user
#             echo "ip6tables -t nat -A POSTROUTING -o $iface_linux -j MASQUERADE"  >> firewall.user
#         fi
          
      - name: Update Target.mk
        run: |
          cd friendlywrt-rk3328/friendlywrt/include
          sed -i 's/dnsmasq /dnsmasq-full default-settings luci /' target.mk

      - name: Update Feeds		
        run: |		
          cd friendlywrt-rk3328/friendlywrt		
          ./scripts/feeds update -a		
          ./scripts/feeds install -a

      - name: Install Mods
        run: |
          cd friendlywrt-rk3328

          if [ -f friendlywrt/feeds/packages/utils/runc/Makefile ]; then
              sed -i '/STAMP_BUILT/d' friendlywrt/feeds/packages/utils/runc/Makefile
          fi
          if [ -f friendlywrt/feeds/packages/utils/containerd/Makefile ]; then
              sed -i '/STAMP_BUILT/d' friendlywrt/feeds/packages/utils/containerd/Makefile
          fi
          
          wget -O friendlywrt/package/feeds/packages/zstd/Makefile https://raw.githubusercontent.com/coolsnowwolf/packages/89080f226affe0815c7fb8ff77f3f2d53058e9ec/utils/zstd/Makefile
          wget -O friendlywrt/package/kernel/kmod-sched-cake/Makefile https://raw.githubusercontent.com/coolsnowwolf/lede/master/package/kernel/kmod-sched-cake-oot/Makefile

          #cp ../patches/31-usb_wifi friendlywrt/package/base-files/files/etc/hotplug.d/usb/31-usb_wifi

          sed -i "/redirect_https/d" friendlywrt/package/network/services/uhttpd/files/uhttpd.config
          sed -i '/Load Average/i\\t\t<tr><td width="33%"><%:CPU Temperature%></td><td><%=luci.sys.exec("cut -c1-2 /sys/class/thermal/thermal_zone0/temp")%><span>&#8451;</span></td></tr>' friendlywrt/feeds/luci/modules/luci-mod-admin-full/luasrc/view/admin_status/index.htm
          sed -i 's/pcdata(boardinfo.system or "?")/"ARMv8"/' friendlywrt/feeds/luci/modules/luci-mod-admin-full/luasrc/view/admin_status/index.htm
          sed -i 's/services/vpn/g' friendlywrt/package/feeds/luci/luci-app-openvpn/luasrc/controller/openvpn.lua
          sed -i 's/<%=luci.sys.exec("cat \/etc\/bench.log") or " "%>//' friendlywrt/feeds/luci/modules/luci-mod-admin-full/luasrc/view/admin_status/index.htm
          sed -i '/luciversion/a \/ by <a href="https://github.com/02015678/NanoPi-R2S">02015678</a>' friendlywrt/feeds/luci/modules/luci-mod-admin-full/luasrc/view/admin_status/index.htm
          sed -i '/firewall\.user/d' friendlywrt/package/lean/default-settings/files/zzz-default-settings
          cp ../scripts/fw_update.sh friendlywrt/package/base-files/files/usr/bin/fw_update
          cp ../scripts/rom_prepare.sh friendlywrt/package/base-files/files/usr/bin/rom_prepare
          cp ../scripts/check_net.sh friendlywrt/package/base-files/files/usr/bin/check_net
          echo "/usr/bin/check_net" >> friendlywrt/package/base-files/files/root/setup.sh

      - name: Add Temperature to Netdata
        run: |
          cd friendlywrt-rk3328
          mkdir -p friendlywrt/package/base-files/files/usr/lib/netdata/charts.d
          cp ../scripts/temp.chart.sh friendlywrt/package/base-files/files/usr/lib/netdata/charts.d/
          echo "sed -i 's/charts.d = no/charts.d = yes/' /etc/netdata/netdata.conf" >> friendlywrt/package/base-files/files/root/setup.sh
          echo "cp /usr/lib/netdata/conf.d/charts.d.conf /etc/netdata/" >> friendlywrt/package/base-files/files/root/setup.sh
          echo "echo 'temp=yes' >> /etc/netdata/charts.d.conf" >> friendlywrt/package/base-files/files/root/setup.sh
          echo "/etc/init.d/netdata restart" >> friendlywrt/package/base-files/files/root/setup.sh
      
      - name: Patch Kernel
        run: |
          cd friendlywrt-rk3328/kernel/
          git apply ../../patches/001-add-full_cone_nat.patch
      
      # - name: Unlock CPU 1.5Ghz
      #   run: |
      #     cd friendlywrt-rk3328/kernel
      #     wget https://github.com/armbian/build/raw/master/patch/kernel/rockchip64-dev/RK3328-enable-1512mhz-opp.patch
      #     git apply RK3328-enable-1512mhz-opp.patch

      - name: Custom Configure Files
        run: |
          rm -f friendlywrt-rk3328/friendlywrt/.config*
          cp r2s-rk3328-fat.config friendlywrt-rk3328/configs/config_rk3328

      - name: Set Default Values
        run: |
          cd friendlywrt-rk3328/friendlywrt
          sed -i '/uci commit luci/i\uci set luci.main.mediaurlbase=/luci-static/argon' package/lean/default-settings/files/zzz-default-settings
           
      - name: Install UPX
        run: |
          ln -s /usr/bin/upx-ucl friendlywrt-rk3328/friendlywrt/staging_dir/host/bin/upx
          
      - name: Build OpenWrt
        run: |
          cd friendlywrt-rk3328
          sed -i 's/set -eu/set -u/' scripts/mk-friendlywrt.sh
          ./build.sh nanopi_r2s.mk

      - name: Fix Rootfs Owner and Group
        run: |
          sudo df -lh
          lodev=$(sudo losetup -f)
          echo "found unused loop dev $lodev"
          sudo losetup -o 100663296 $lodev friendlywrt-rk3328/out/*.img
          sudo rm -rf /mnt/friendlywrt-tmp
          sudo mkdir -p /mnt/friendlywrt-tmp
          sudo mount $lodev /mnt/friendlywrt-tmp
          sudo chown -R root:root /mnt/friendlywrt-tmp
          sudo umount /mnt/friendlywrt-tmp
          sudo losetup -d $lodev

      - name: Assemble Artifact
        id: assemble_artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          touch ./artifact/md5sum.txt

          find friendlywrt-rk3328/out/ -name "FriendlyWrt_*img*" | xargs -I{} sh -c 'f=$(basename $1); zip -r -j "./artifact/${f}.zip" $1' sh {} \;
          
          cp friendlywrt-rk3328/friendlywrt/.config                                   ./artifact/  
          cp friendlywrt-rk3328/friendlywrt/bin/packages/*/*/luci-app-r2sflasher*.ipk ./artifact/   || echo "[WARNING] No luci-app-r2sflasher*.ipk generated"
          cp friendlywrt-rk3328/friendlywrt/bin/packages/*/*/luci-app-passwall*.ipk   ./artifact/   || echo "[WARNING] No luci-app-passwall*.ipk generated"
          cp friendlywrt-rk3328/friendlywrt/bin/packages/*/*/luci-app-ssr-plus*.ipk   ./artifact/   || echo "[WARNING] No luci-app-ssr-plus*.ipk generated"
          cp friendlywrt-rk3328/friendlywrt/bin/packages/*/*/luci-app-openclash*.ipk  ./artifact/   || echo "[WARNING] No luci-app-openclash*.ipk generated"
          
          md5sum ./artifact/*img* >> ./artifact/md5sum.txt
          md5sum ./artifact/*.ipk >> ./artifact/md5sum.txt
          sed -i 's|./artifact/||' ./artifact/md5sum.txt
          
          zip -r artifact.zip ./artifact/
          release_tag="R2S-Fat-$(date +%Y-%m-%d)"
          echo "##[set-output name=release_tag;]$release_tag"
          
      - name: Upload Artifact
        id: upload_artifact
        uses: actions/upload-artifact@master
        with:
          name: FriendlyWrt_NanoPi-R2S RK3328 v19.07 Fat ROM
          path: ./artifact/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.assemble_artifact.outputs.release_tag }}
          release_name: FriendlyWrt NanoPi-R2S RK3328 Openwrt 19.07 ${{ steps.assemble_artifact.outputs.release_tag }}
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./artifact.zip
          asset_name: ${{ steps.assemble_artifact.outputs.release_tag }}-ROM.zip
          asset_content_type: application/zip
